-- ============================================================
-- SEED: 11 Very High Complexity Reports → dbMasterLaporan
-- Generated by: dynamic-report-seed-engine
-- Date: 2026-08-06
-- ============================================================
USE dbbcagroup;
GO

SET IDENTITY_INSERT dbMasterLaporan ON;
GO

-- ============================================================
-- INSERT 11 LAPORAN BARU KE dbMasterLaporan
-- ID 100-110 (existing range 2-24, gunakan range baru)
-- ============================================================
INSERT INTO dbMasterLaporan
    (id_laporan, KODEMENU, nama_laporan, deskripsi, query_sumber_data, status_aktif, footer_bands)
VALUES
(100, '0303301',
 'Invoice Penjualan Detail',
 'very-high-complexity report - Invoice Penjualan Detail (Score 1217.82)',
 'EXEC Sp_ReportInvoicePenjualanDet @SReport=''T'', @Ordr=''S'', @tgl1=''2024-01-01'', @tgl2=''2024-12-31'', @isiList='''', @NeedOto=''0'', @isKP=''0'', @PPN=1, @Id=''%''',
 1,
 '{"bands":{"title":{"enabled":true,"content":"LAPORAN INVOICE PENJUALAN DETAIL","align":"center"},"pageHeader":{"enabled":true,"content":"Periode: @tgl1 s/d @tgl2"},"summary":{"enabled":true,"layout":{"columns":3,"alignment":"spread"},"signatures":[{"label":"Kontrol","position":"left"},{"label":"Sales","position":"center"},{"label":"Pimpinan","position":"right"}]}}}'
),

(101, '0303302',
 'Invoice Penjualan Rekening',
 'very-high-complexity report - Invoice Penjualan Rekening (Score 945.77)',
 'EXEC Sp_ReportInvoicePenjualanRek @Choice=''B'', @Tgl1=''2024-01-01'', @Tgl2=''2024-12-31'', @NeedOto=0, @PPN=1, @Id=''%''',
 1,
 '{"bands":{"title":{"enabled":true,"content":"INVOICE PENJUALAN REKAP","align":"center"},"summary":{"enabled":true,"signatures":[{"label":"Accounting","position":"left"},{"label":"Finance Manager","position":"right"}]}}}'
),

(102, '025801',
 'Transfer In Detail',
 'very-high-complexity report - Transfer Masuk (Score 773.45)',
 'EXEC sp_TFTransIn @Nobukti=''%'', @Do=''I'', @Urut=1',
 1,
 '{"bands":{"title":{"enabled":true,"content":"LAPORAN TRANSFER IN","align":"center"},"summary":{"enabled":true,"signatures":[{"label":"Teller","position":"left"},{"label":"Pincab","position":"right"}]}}}'
),

(103, '020507',
 'Buku Besar Rekening',
 'very-high-complexity report - Buku Besar (Score 732.88)',
 'EXEC Sp_reportBPrek @Choice=''B'', @Tgl1=''2024-01-01'', @Tgl2=''2024-12-31'', @NeedOto=0, @Id=''%''',
 1,
 '{"bands":{"title":{"enabled":true,"content":"BUKU BESAR PER REKENING","align":"center"},"summary":{"enabled":true,"signatures":[{"label":"Accounting","position":"left"},{"label":"Auditor","position":"right"}]}}}'
),

(104, '0303303',
 'Rekap Invoice Penjualan',
 'very-high-complexity report - Recurring Invoice (Score 688.94)',
 'EXEC Sp_ReportRInvoicePenjualanRek @Choice=''B'', @Tgl1=''2024-01-01'', @Tgl2=''2024-12-31'', @Needoto=0, @Id=''%''',
 1,
 '{"bands":{"title":{"enabled":true,"content":"REKAP INVOICE PENJUALAN","align":"center"},"summary":{"enabled":true,"signatures":[{"label":"Kontrol","position":"left"},{"label":"Manager","position":"center"},{"label":"Pimpinan","position":"right"}]}}}'
),

(105, '0303304',
 'Penjualan Gudang Rekening',
 'very-high-complexity report - Penjualan Gudang Rek (Score 685.15)',
 'EXEC Sp_ReportRPenjualanGdgRek @Choice=''B'', @Tgl1=''2024-01-01'', @Tgl2=''2024-12-31'', @Needoto=0, @Id=''%''',
 1,
 '{"bands":{"title":{"enabled":true,"content":"PENJUALAN GUDANG REKAP","align":"center"},"summary":{"enabled":true,"signatures":[{"label":"Gudang","position":"left"},{"label":"Penjualan","position":"center"},{"label":"Pimpinan","position":"right"}]}}}'
),

(106, '025902',
 'Pembelian ACC Rekening',
 'very-high-complexity report - Pembelian ACC (Score 638.50)',
 'EXEC Sp_ReportBeliACCRek @Choice=''B'', @Tgl1=''2024-01-01'', @Tgl2=''2024-12-31'', @NeedOto=0, @TipeBayar=0, @Id=''%''',
 1,
 '{"bands":{"title":{"enabled":true,"content":"LAPORAN PEMBELIAN ACC","align":"center"},"summary":{"enabled":true,"signatures":[{"label":"Pembelian","position":"left"},{"label":"Finance","position":"right"}]}}}'
),

(107, '020406',
 'Piutang Surat Jalan',
 'very-high-complexity report - Piutang SJ (Score 504.21)',
 'EXEC sp_ReportPiutangSrtJln @Bulan=12, @Tahun=2024, @Id=''%''',
 1,
 '{"bands":{"title":{"enabled":true,"content":"PIUTANG SURAT JALAN","align":"center"},"summary":{"enabled":true,"signatures":[{"label":"Collection","position":"left"},{"label":"Finance Manager","position":"right"}]}}}'
),

(108, '025802',
 'Transfer Out Detail',
 'very-high-complexity report - Transfer Keluar (Score 493.18)',
 'EXEC sp_TFTransOut @Nobukti=''%'', @Do=''O'', @Urut=1',
 1,
 '{"bands":{"title":{"enabled":true,"content":"LAPORAN TRANSFER OUT","align":"center"},"summary":{"enabled":true,"signatures":[{"label":"Teller","position":"left"},{"label":"Pincab","position":"right"}]}}}'
),

(109, '050102',
 'Stock Quantity Rupiah',
 'very-high-complexity report - Stock Qty Rp (Score 479.10)',
 'EXEC Sp_reportStockQtyRp @Bulan=12, @Tahun=2024, @isi=2, @Kodegdg=''%'', @KodeGrp=''%'', @minus=0, @MinusHpp=0, @Qty1=1, @Qty2=1, @Pilih=1, @KodeSubGrp=''%''',
 1,
 '{"bands":{"title":{"enabled":true,"content":"LAPORAN STOCK QUANTITY & RUPIAH","align":"center"},"summary":{"enabled":true,"signatures":[{"label":"Gudang","position":"left"},{"label":"PPIC","position":"center"},{"label":"Pimpinan","position":"right"}]}}}'
),

(110, '050103',
 'Stock Quantity Rekonsiliasi',
 'very-high-complexity report - Stock Rekonsiliasi (Score 474.81)',
 'EXEC sp_reportStockQtyRprek @Bulan=12, @Tahun=2024, @isi=2, @Kodegdg=''%'', @KodeGrp=''%'', @minus=0, @MinusHPP=0, @Qty1=1, @Qty2=1, @Pilih=1, @KodeSubGrp=''%''',
 1,
 '{"bands":{"title":{"enabled":true,"content":"STOCK QUANTITY REKONSILIASI","align":"center"},"summary":{"enabled":true,"signatures":[{"label":"Accounting","position":"left"},{"label":"Gudang","position":"center"},{"label":"Pimpinan","position":"right"}]}}}'
);

SET IDENTITY_INSERT dbMasterLaporan OFF;
GO

PRINT '11 laporan baru inserted ke dbMasterLaporan (id 100-110)';
GO

SELECT id_laporan, KODEMENU, nama_laporan FROM dbMasterLaporan
WHERE id_laporan BETWEEN 100 AND 110 ORDER BY id_laporan;
GO