-- ============================================================
-- MASTER SEED SCRIPT: 9 Complex Reports (Corrected)
-- Generated by: dynamic-report-seed-engine
-- Date: 2026-08-06
-- Notes:
--   - 050102 dan 050103 sudah ada di dbMasterLaporan (id 20, 21) → skip insert
--   - 020507 dan 020406 sudah ada di DBMENUREPORT → gunakan untuk dbMasterLaporan
--   - 7 KODEMENU baru ditambahkan ke DBMENUREPORT dulu
-- ============================================================
USE dbbcagroup;
GO

PRINT '========================================';
PRINT '  SEED: 9 Complex Reports Master Data';
PRINT '========================================';
PRINT '';
GO

-- Step 1: DBMENUREPORT (7 KODEMENU baru)
PRINT '1. Seeding DBMENUREPORT (7 KODEMENU baru)...';
GO
-- Execute: seed_dbMasterLaporan_9_reports.sql (includes DBMENUREPORT insert)
GO

-- Step 2: dbMasterLaporan (9 rows, id 25-35)
PRINT '2. Seeding dbMasterLaporan...';
GO
-- Execute: seed_dbMasterLaporan_9_reports.sql
GO

-- Step 3: dbParameterLaporan (73 rows)
PRINT '3. Seeding dbParameterLaporan...';
GO
-- Execute: seed_dbParameterLaporan_9_reports.sql
GO

-- Step 4: dbKolomLaporan (66 rows)
PRINT '4. Seeding dbKolomLaporan...';
GO
-- Execute: seed_dbKolomLaporan_9_reports.sql
GO

-- Step 5: dbQueryLaporan (11 rows)
PRINT '5. Seeding dbQueryLaporan...';
GO
-- Execute: seed_dbQueryLaporan_9_reports.sql
GO

-- Step 6: dbGroupLaporan (3 rows)
PRINT '6. Seeding dbGroupLaporan...';
GO
-- Execute: seed_dbGroupLaporan_9_reports.sql
GO

-- Step 7: DBFLMENUREPORT (Access control)
PRINT '7. Granting access in DBFLMENUREPORT...';
GO
-- Execute: seed_DBFLMENUREPORT_9_reports.sql
GO

-- Summary
PRINT '';
PRINT '========================================';
PRINT '  SEED SUMMARY';
PRINT '========================================';
PRINT '';

SELECT 
    'dbMasterLaporan' as TableName, COUNT(*) as Rows 
    FROM dbMasterLaporan WHERE id_laporan BETWEEN 25 AND 35
UNION ALL
SELECT 'dbParameterLaporan', COUNT(*) FROM dbParameterLaporan WHERE id_laporan BETWEEN 25 AND 35
UNION ALL
SELECT 'dbKolomLaporan', COUNT(*) FROM dbKolomLaporan WHERE id_laporan BETWEEN 25 AND 35
UNION ALL
SELECT 'dbQueryLaporan', COUNT(*) FROM dbQueryLaporan WHERE id_laporan BETWEEN 25 AND 35
UNION ALL
SELECT 'dbGroupLaporan', COUNT(*) FROM dbGroupLaporan WHERE id_laporan BETWEEN 25 AND 35
UNION ALL
SELECT 'DBFLMENUREPORT', COUNT(DISTINCT L1) FROM DBFLMENUREPORT 
WHERE L1 IN ('020507','020406','0303301','0303302','025801','0303303','0303304','025902','025802','050102','050103');
GO

PRINT '';
PRINT '========================================';
PRINT '  SEED COMPLETE';
PRINT '========================================';
GO