-- ============================================================
-- MASTER SEED SCRIPT: 11 Very High Complexity Reports
-- Generated by: dynamic-report-seed-engine
-- Date: 2026-08-06
-- Usage: Execute all 5 scripts in order
-- ============================================================
USE dbbcagroup;
GO

PRINT '========================================';
PRINT '  SEED: 11 Complex Reports Master Data';
PRINT '========================================';
PRINT '';
GO

-- Step 1: dbMasterLaporan (11 rows)
PRINT '1. Seeding dbMasterLaporan...';
GO
-- Execute: seed_dbMasterLaporan_11_reports.sql
GO

-- Step 2: dbParameterLaporan (70 rows)
PRINT '2. Seeding dbParameterLaporan...';
GO
-- Execute: seed_dbParameterLaporan_11_reports.sql
GO

-- Step 3: dbKolomLaporan (71 rows)
PRINT '3. Seeding dbKolomLaporan...';
GO
-- Execute: seed_dbKolomLaporan_11_reports.sql
GO

-- Step 4: dbQueryLaporan (11 rows)
PRINT '4. Seeding dbQueryLaporan...';
GO
-- Execute: seed_dbQueryLaporan_11_reports.sql
GO

-- Step 5: dbGroupLaporan (3 rows)
PRINT '5. Seeding dbGroupLaporan...';
GO
-- Execute: seed_dbGroupLaporan_11_reports.sql
GO

-- Step 6: DBFLMENUREPORT (Access control)
PRINT '6. Granting access in DBFLMENUREPORT...';
GO
-- Execute: seed_DBFLMENUREPORT_11_reports.sql
GO

-- Summary
PRINT '';
PRINT '========================================';
PRINT '  SEED SUMMARY';
PRINT '========================================';
PRINT '';

SELECT 
    'dbMasterLaporan' as TableName, COUNT(*) as Rows 
    FROM dbMasterLaporan WHERE id_laporan BETWEEN 100 AND 110
UNION ALL
SELECT 'dbParameterLaporan', COUNT(*) FROM dbParameterLaporan WHERE id_laporan BETWEEN 100 AND 169
UNION ALL
SELECT 'dbKolomLaporan', COUNT(*) FROM dbKolomLaporan WHERE id_laporan BETWEEN 100 AND 184
UNION ALL
SELECT 'dbQueryLaporan', COUNT(*) FROM dbQueryLaporan WHERE id_laporan BETWEEN 100 AND 110
UNION ALL
SELECT 'dbGroupLaporan', COUNT(*) FROM dbGroupLaporan WHERE id_laporan BETWEEN 100 AND 110
UNION ALL
SELECT 'DBFLMENUREPORT', COUNT(DISTINCT L1) FROM DBFLMENUREPORT 
WHERE L1 IN ('0303301','0303302','025801','020507','0303303','0303304','025902','020406','025802','050102','050103');
GO

PRINT '';
PRINT '========================================';
PRINT '  SEED COMPLETE';
PRINT '========================================';
GO