/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R400RouteImport } from './routes/400'
import { Route as R404RouteImport } from './routes/404'
import { Route as R500RouteImport } from './routes/500'
import { Route as AboutRouteImport } from './routes/about'
import { Route as publicDocsRouteImport } from './routes/(public)/docs'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as KaryawanLayoutRouteImport } from './routes/karyawan/_layout'
import { Route as publicDocsIndexRouteImport } from './routes/(public)/docs/index'
import { Route as publicDocsDataRouteImport } from './routes/(public)/docs/data'
import { Route as publicDocsFeedbackRouteImport } from './routes/(public)/docs/feedback'
import { Route as publicDocsFormRouteImport } from './routes/(public)/docs/form'
import { Route as publicDocsLayoutRouteImport } from './routes/(public)/docs/layout'
import { Route as publicDocsNavigationRouteImport } from './routes/(public)/docs/navigation'
import { Route as publicDocsOverlayRouteImport } from './routes/(public)/docs/overlay'
import { Route as publicDocsThemeRouteImport } from './routes/(public)/docs/theme'
import { Route as publicauthLoginIndexRouteImport } from './routes/(public)/(auth)/login/index'
import { Route as publicauthRegisterIndexRouteImport } from './routes/(public)/(auth)/register/index'
import { Route as AdminLayoutBerkasMenuRouteImport } from './routes/admin/_layout/berkas/menu'
import { Route as AdminLayoutBerkasPerusahaanRouteImport } from './routes/admin/_layout/berkas/perusahaan'
import { Route as AdminLayoutDashboardIndexRouteImport } from './routes/admin/_layout/dashboard/index'
import { Route as AdminLayoutDocumentsIndexRouteImport } from './routes/admin/_layout/documents/index'
import { Route as AdminLayoutReportsBuilderRouteImport } from './routes/admin/_layout/reports/builder'
import { Route as AdminLayoutReportsLaporanRouteImport } from './routes/admin/_layout/reports/laporan'
import { Route as KaryawanLayoutDashboardIndexRouteImport } from './routes/karyawan/_layout/dashboard/index'
import { Route as AdminLayoutAccountingKasbankIndexRouteImport } from './routes/admin/_layout/accounting/kasbank/index'
import { Route as AdminLayoutAccountingKasbankNobuktiRouteImport } from './routes/admin/_layout/accounting/kasbank/$nobukti'
import { Route as AdminLayoutMasterDataActivityLogsIndexRouteImport } from './routes/admin/_layout/master-data/activity-logs/index'
import { Route as AdminLayoutMasterDataConfigLogsIndexRouteImport } from './routes/admin/_layout/master-data/config-logs/index'
import { Route as AdminLayoutMasterDataDynamicBrowseIndexRouteImport } from './routes/admin/_layout/master-data/dynamic-browse/index'
import { Route as AdminLayoutMasterDataLaporanDinamisIndexRouteImport } from './routes/admin/_layout/master-data/laporan-dinamis/index'
import { Route as AdminLayoutMasterDataUsersIndexRouteImport } from './routes/admin/_layout/master-data/users/index'
import { Route as AdminLayoutReportsBuilderIndexRouteImport } from './routes/admin/_layout/reports/builder/index'
import { Route as AdminLayoutReportsLaporanIndexRouteImport } from './routes/admin/_layout/reports/laporan/index'
import { Route as AdminLayoutReportsLaporanKodeMenuRouteImport } from './routes/admin/_layout/reports/laporan/$kodeMenu'
import { Route as AdminLayoutReportsPermissionReportIndexRouteImport } from './routes/admin/_layout/reports/permission-report/index'
import { Route as KaryawanLayoutBerkasLaporanDinamisIndexRouteImport } from './routes/karyawan/_layout/berkas/laporan-dinamis/index'
import { Route as KaryawanLayoutBerkasLaporanDinamisKodeRouteImport } from './routes/karyawan/_layout/berkas/laporan-dinamis/$kode'
import { Route as AdminLayoutMasterDataUsersIdIndexRouteImport } from './routes/admin/_layout/master-data/users/$id/index'
import { Route as AdminLayoutMasterDataUsersNewIndexRouteImport } from './routes/admin/_layout/master-data/users/new/index'
import { Route as AdminLayoutReportsBuilderKodemenuEditRouteImport } from './routes/admin/_layout/reports/builder/$kodemenu/edit'
import { Route as AdminLayoutReportsBuilderKodemenuGenerateRouteImport } from './routes/admin/_layout/reports/builder/$kodemenu/generate'
import { Route as AdminLayoutMasterDataUsersIdEditIndexRouteImport } from './routes/admin/_layout/master-data/users/$id/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R400Route = R400RouteImport.update({
  id: '/400',
  path: '/400',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDocsRoute = publicDocsRouteImport.update({
  id: '/(public)/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KaryawanLayoutRoute = KaryawanLayoutRouteImport.update({
  id: '/karyawan/_layout',
  path: '/karyawan',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDocsIndexRoute = publicDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsDataRoute = publicDocsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsFeedbackRoute = publicDocsFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsFormRoute = publicDocsFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsLayoutRoute = publicDocsLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsNavigationRoute = publicDocsNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsOverlayRoute = publicDocsOverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicDocsThemeRoute = publicDocsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => publicDocsRoute,
} as any)
const publicauthLoginIndexRoute = publicauthLoginIndexRouteImport.update({
  id: '/(public)/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthRegisterIndexRoute = publicauthRegisterIndexRouteImport.update({
  id: '/(public)/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutBerkasMenuRoute = AdminLayoutBerkasMenuRouteImport.update({
  id: '/berkas/menu',
  path: '/berkas/menu',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBerkasPerusahaanRoute =
  AdminLayoutBerkasPerusahaanRouteImport.update({
    id: '/berkas/perusahaan',
    path: '/berkas/perusahaan',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutDashboardIndexRoute =
  AdminLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutDocumentsIndexRoute =
  AdminLayoutDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutReportsBuilderRoute =
  AdminLayoutReportsBuilderRouteImport.update({
    id: '/reports/builder',
    path: '/reports/builder',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutReportsLaporanRoute =
  AdminLayoutReportsLaporanRouteImport.update({
    id: '/reports/laporan',
    path: '/reports/laporan',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const KaryawanLayoutDashboardIndexRoute =
  KaryawanLayoutDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => KaryawanLayoutRoute,
  } as any)
const AdminLayoutAccountingKasbankIndexRoute =
  AdminLayoutAccountingKasbankIndexRouteImport.update({
    id: '/accounting/kasbank/',
    path: '/accounting/kasbank/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutAccountingKasbankNobuktiRoute =
  AdminLayoutAccountingKasbankNobuktiRouteImport.update({
    id: '/accounting/kasbank/$nobukti',
    path: '/accounting/kasbank/$nobukti',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMasterDataActivityLogsIndexRoute =
  AdminLayoutMasterDataActivityLogsIndexRouteImport.update({
    id: '/master-data/activity-logs/',
    path: '/master-data/activity-logs/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMasterDataConfigLogsIndexRoute =
  AdminLayoutMasterDataConfigLogsIndexRouteImport.update({
    id: '/master-data/config-logs/',
    path: '/master-data/config-logs/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMasterDataDynamicBrowseIndexRoute =
  AdminLayoutMasterDataDynamicBrowseIndexRouteImport.update({
    id: '/master-data/dynamic-browse/',
    path: '/master-data/dynamic-browse/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMasterDataLaporanDinamisIndexRoute =
  AdminLayoutMasterDataLaporanDinamisIndexRouteImport.update({
    id: '/master-data/laporan-dinamis/',
    path: '/master-data/laporan-dinamis/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMasterDataUsersIndexRoute =
  AdminLayoutMasterDataUsersIndexRouteImport.update({
    id: '/master-data/users/',
    path: '/master-data/users/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutReportsBuilderIndexRoute =
  AdminLayoutReportsBuilderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutReportsBuilderRoute,
  } as any)
const AdminLayoutReportsLaporanIndexRoute =
  AdminLayoutReportsLaporanIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminLayoutReportsLaporanRoute,
  } as any)
const AdminLayoutReportsLaporanKodeMenuRoute =
  AdminLayoutReportsLaporanKodeMenuRouteImport.update({
    id: '/$kodeMenu',
    path: '/$kodeMenu',
    getParentRoute: () => AdminLayoutReportsLaporanRoute,
  } as any)
const AdminLayoutReportsPermissionReportIndexRoute =
  AdminLayoutReportsPermissionReportIndexRouteImport.update({
    id: '/reports/permission-report/',
    path: '/reports/permission-report/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const KaryawanLayoutBerkasLaporanDinamisIndexRoute =
  KaryawanLayoutBerkasLaporanDinamisIndexRouteImport.update({
    id: '/berkas/laporan-dinamis/',
    path: '/berkas/laporan-dinamis/',
    getParentRoute: () => KaryawanLayoutRoute,
  } as any)
const KaryawanLayoutBerkasLaporanDinamisKodeRoute =
  KaryawanLayoutBerkasLaporanDinamisKodeRouteImport.update({
    id: '/berkas/laporan-dinamis/$kode',
    path: '/berkas/laporan-dinamis/$kode',
    getParentRoute: () => KaryawanLayoutRoute,
  } as any)
const AdminLayoutMasterDataUsersIdIndexRoute =
  AdminLayoutMasterDataUsersIdIndexRouteImport.update({
    id: '/master-data/users/$id/',
    path: '/master-data/users/$id/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutMasterDataUsersNewIndexRoute =
  AdminLayoutMasterDataUsersNewIndexRouteImport.update({
    id: '/master-data/users/new/',
    path: '/master-data/users/new/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutReportsBuilderKodemenuEditRoute =
  AdminLayoutReportsBuilderKodemenuEditRouteImport.update({
    id: '/$kodemenu/edit',
    path: '/$kodemenu/edit',
    getParentRoute: () => AdminLayoutReportsBuilderRoute,
  } as any)
const AdminLayoutReportsBuilderKodemenuGenerateRoute =
  AdminLayoutReportsBuilderKodemenuGenerateRouteImport.update({
    id: '/$kodemenu/generate',
    path: '/$kodemenu/generate',
    getParentRoute: () => AdminLayoutReportsBuilderRoute,
  } as any)
const AdminLayoutMasterDataUsersIdEditIndexRoute =
  AdminLayoutMasterDataUsersIdEditIndexRouteImport.update({
    id: '/master-data/users/$id/edit/',
    path: '/master-data/users/$id/edit/',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/400': typeof R400Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/docs': typeof publicDocsRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/karyawan': typeof KaryawanLayoutRouteWithChildren
  '/docs/data': typeof publicDocsDataRoute
  '/docs/feedback': typeof publicDocsFeedbackRoute
  '/docs/form': typeof publicDocsFormRoute
  '/docs/layout': typeof publicDocsLayoutRoute
  '/docs/navigation': typeof publicDocsNavigationRoute
  '/docs/overlay': typeof publicDocsOverlayRoute
  '/docs/theme': typeof publicDocsThemeRoute
  '/docs/': typeof publicDocsIndexRoute
  '/admin/berkas/menu': typeof AdminLayoutBerkasMenuRoute
  '/admin/berkas/perusahaan': typeof AdminLayoutBerkasPerusahaanRoute
  '/admin/reports/builder': typeof AdminLayoutReportsBuilderRouteWithChildren
  '/admin/reports/laporan': typeof AdminLayoutReportsLaporanRouteWithChildren
  '/login/': typeof publicauthLoginIndexRoute
  '/register/': typeof publicauthRegisterIndexRoute
  '/admin/dashboard/': typeof AdminLayoutDashboardIndexRoute
  '/admin/documents/': typeof AdminLayoutDocumentsIndexRoute
  '/karyawan/dashboard/': typeof KaryawanLayoutDashboardIndexRoute
  '/admin/accounting/kasbank/$nobukti': typeof AdminLayoutAccountingKasbankNobuktiRoute
  '/admin/reports/laporan/$kodeMenu': typeof AdminLayoutReportsLaporanKodeMenuRoute
  '/karyawan/berkas/laporan-dinamis/$kode': typeof KaryawanLayoutBerkasLaporanDinamisKodeRoute
  '/admin/accounting/kasbank/': typeof AdminLayoutAccountingKasbankIndexRoute
  '/admin/master-data/activity-logs/': typeof AdminLayoutMasterDataActivityLogsIndexRoute
  '/admin/master-data/config-logs/': typeof AdminLayoutMasterDataConfigLogsIndexRoute
  '/admin/master-data/dynamic-browse/': typeof AdminLayoutMasterDataDynamicBrowseIndexRoute
  '/admin/master-data/laporan-dinamis/': typeof AdminLayoutMasterDataLaporanDinamisIndexRoute
  '/admin/master-data/users/': typeof AdminLayoutMasterDataUsersIndexRoute
  '/admin/reports/builder/': typeof AdminLayoutReportsBuilderIndexRoute
  '/admin/reports/laporan/': typeof AdminLayoutReportsLaporanIndexRoute
  '/admin/reports/permission-report/': typeof AdminLayoutReportsPermissionReportIndexRoute
  '/karyawan/berkas/laporan-dinamis/': typeof KaryawanLayoutBerkasLaporanDinamisIndexRoute
  '/admin/reports/builder/$kodemenu/edit': typeof AdminLayoutReportsBuilderKodemenuEditRoute
  '/admin/reports/builder/$kodemenu/generate': typeof AdminLayoutReportsBuilderKodemenuGenerateRoute
  '/admin/master-data/users/$id/': typeof AdminLayoutMasterDataUsersIdIndexRoute
  '/admin/master-data/users/new/': typeof AdminLayoutMasterDataUsersNewIndexRoute
  '/admin/master-data/users/$id/edit/': typeof AdminLayoutMasterDataUsersIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/400': typeof R400Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/karyawan': typeof KaryawanLayoutRouteWithChildren
  '/docs/data': typeof publicDocsDataRoute
  '/docs/feedback': typeof publicDocsFeedbackRoute
  '/docs/form': typeof publicDocsFormRoute
  '/docs/layout': typeof publicDocsLayoutRoute
  '/docs/navigation': typeof publicDocsNavigationRoute
  '/docs/overlay': typeof publicDocsOverlayRoute
  '/docs/theme': typeof publicDocsThemeRoute
  '/docs': typeof publicDocsIndexRoute
  '/admin/berkas/menu': typeof AdminLayoutBerkasMenuRoute
  '/admin/berkas/perusahaan': typeof AdminLayoutBerkasPerusahaanRoute
  '/login': typeof publicauthLoginIndexRoute
  '/register': typeof publicauthRegisterIndexRoute
  '/admin/dashboard': typeof AdminLayoutDashboardIndexRoute
  '/admin/documents': typeof AdminLayoutDocumentsIndexRoute
  '/karyawan/dashboard': typeof KaryawanLayoutDashboardIndexRoute
  '/admin/accounting/kasbank/$nobukti': typeof AdminLayoutAccountingKasbankNobuktiRoute
  '/admin/reports/laporan/$kodeMenu': typeof AdminLayoutReportsLaporanKodeMenuRoute
  '/karyawan/berkas/laporan-dinamis/$kode': typeof KaryawanLayoutBerkasLaporanDinamisKodeRoute
  '/admin/accounting/kasbank': typeof AdminLayoutAccountingKasbankIndexRoute
  '/admin/master-data/activity-logs': typeof AdminLayoutMasterDataActivityLogsIndexRoute
  '/admin/master-data/config-logs': typeof AdminLayoutMasterDataConfigLogsIndexRoute
  '/admin/master-data/dynamic-browse': typeof AdminLayoutMasterDataDynamicBrowseIndexRoute
  '/admin/master-data/laporan-dinamis': typeof AdminLayoutMasterDataLaporanDinamisIndexRoute
  '/admin/master-data/users': typeof AdminLayoutMasterDataUsersIndexRoute
  '/admin/reports/builder': typeof AdminLayoutReportsBuilderIndexRoute
  '/admin/reports/laporan': typeof AdminLayoutReportsLaporanIndexRoute
  '/admin/reports/permission-report': typeof AdminLayoutReportsPermissionReportIndexRoute
  '/karyawan/berkas/laporan-dinamis': typeof KaryawanLayoutBerkasLaporanDinamisIndexRoute
  '/admin/reports/builder/$kodemenu/edit': typeof AdminLayoutReportsBuilderKodemenuEditRoute
  '/admin/reports/builder/$kodemenu/generate': typeof AdminLayoutReportsBuilderKodemenuGenerateRoute
  '/admin/master-data/users/$id': typeof AdminLayoutMasterDataUsersIdIndexRoute
  '/admin/master-data/users/new': typeof AdminLayoutMasterDataUsersNewIndexRoute
  '/admin/master-data/users/$id/edit': typeof AdminLayoutMasterDataUsersIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/400': typeof R400Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/(public)/docs': typeof publicDocsRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/karyawan/_layout': typeof KaryawanLayoutRouteWithChildren
  '/(public)/docs/data': typeof publicDocsDataRoute
  '/(public)/docs/feedback': typeof publicDocsFeedbackRoute
  '/(public)/docs/form': typeof publicDocsFormRoute
  '/(public)/docs/layout': typeof publicDocsLayoutRoute
  '/(public)/docs/navigation': typeof publicDocsNavigationRoute
  '/(public)/docs/overlay': typeof publicDocsOverlayRoute
  '/(public)/docs/theme': typeof publicDocsThemeRoute
  '/(public)/docs/': typeof publicDocsIndexRoute
  '/admin/_layout/berkas/menu': typeof AdminLayoutBerkasMenuRoute
  '/admin/_layout/berkas/perusahaan': typeof AdminLayoutBerkasPerusahaanRoute
  '/admin/_layout/reports/builder': typeof AdminLayoutReportsBuilderRouteWithChildren
  '/admin/_layout/reports/laporan': typeof AdminLayoutReportsLaporanRouteWithChildren
  '/(public)/(auth)/login/': typeof publicauthLoginIndexRoute
  '/(public)/(auth)/register/': typeof publicauthRegisterIndexRoute
  '/admin/_layout/dashboard/': typeof AdminLayoutDashboardIndexRoute
  '/admin/_layout/documents/': typeof AdminLayoutDocumentsIndexRoute
  '/karyawan/_layout/dashboard/': typeof KaryawanLayoutDashboardIndexRoute
  '/admin/_layout/accounting/kasbank/$nobukti': typeof AdminLayoutAccountingKasbankNobuktiRoute
  '/admin/_layout/reports/laporan/$kodeMenu': typeof AdminLayoutReportsLaporanKodeMenuRoute
  '/karyawan/_layout/berkas/laporan-dinamis/$kode': typeof KaryawanLayoutBerkasLaporanDinamisKodeRoute
  '/admin/_layout/accounting/kasbank/': typeof AdminLayoutAccountingKasbankIndexRoute
  '/admin/_layout/master-data/activity-logs/': typeof AdminLayoutMasterDataActivityLogsIndexRoute
  '/admin/_layout/master-data/config-logs/': typeof AdminLayoutMasterDataConfigLogsIndexRoute
  '/admin/_layout/master-data/dynamic-browse/': typeof AdminLayoutMasterDataDynamicBrowseIndexRoute
  '/admin/_layout/master-data/laporan-dinamis/': typeof AdminLayoutMasterDataLaporanDinamisIndexRoute
  '/admin/_layout/master-data/users/': typeof AdminLayoutMasterDataUsersIndexRoute
  '/admin/_layout/reports/builder/': typeof AdminLayoutReportsBuilderIndexRoute
  '/admin/_layout/reports/laporan/': typeof AdminLayoutReportsLaporanIndexRoute
  '/admin/_layout/reports/permission-report/': typeof AdminLayoutReportsPermissionReportIndexRoute
  '/karyawan/_layout/berkas/laporan-dinamis/': typeof KaryawanLayoutBerkasLaporanDinamisIndexRoute
  '/admin/_layout/reports/builder/$kodemenu/edit': typeof AdminLayoutReportsBuilderKodemenuEditRoute
  '/admin/_layout/reports/builder/$kodemenu/generate': typeof AdminLayoutReportsBuilderKodemenuGenerateRoute
  '/admin/_layout/master-data/users/$id/': typeof AdminLayoutMasterDataUsersIdIndexRoute
  '/admin/_layout/master-data/users/new/': typeof AdminLayoutMasterDataUsersNewIndexRoute
  '/admin/_layout/master-data/users/$id/edit/': typeof AdminLayoutMasterDataUsersIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/400'
    | '/404'
    | '/500'
    | '/about'
    | '/docs'
    | '/admin'
    | '/karyawan'
    | '/docs/data'
    | '/docs/feedback'
    | '/docs/form'
    | '/docs/layout'
    | '/docs/navigation'
    | '/docs/overlay'
    | '/docs/theme'
    | '/docs/'
    | '/admin/berkas/menu'
    | '/admin/berkas/perusahaan'
    | '/admin/reports/builder'
    | '/admin/reports/laporan'
    | '/login/'
    | '/register/'
    | '/admin/dashboard/'
    | '/admin/documents/'
    | '/karyawan/dashboard/'
    | '/admin/accounting/kasbank/$nobukti'
    | '/admin/reports/laporan/$kodeMenu'
    | '/karyawan/berkas/laporan-dinamis/$kode'
    | '/admin/accounting/kasbank/'
    | '/admin/master-data/activity-logs/'
    | '/admin/master-data/config-logs/'
    | '/admin/master-data/dynamic-browse/'
    | '/admin/master-data/laporan-dinamis/'
    | '/admin/master-data/users/'
    | '/admin/reports/builder/'
    | '/admin/reports/laporan/'
    | '/admin/reports/permission-report/'
    | '/karyawan/berkas/laporan-dinamis/'
    | '/admin/reports/builder/$kodemenu/edit'
    | '/admin/reports/builder/$kodemenu/generate'
    | '/admin/master-data/users/$id/'
    | '/admin/master-data/users/new/'
    | '/admin/master-data/users/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/400'
    | '/404'
    | '/500'
    | '/about'
    | '/admin'
    | '/karyawan'
    | '/docs/data'
    | '/docs/feedback'
    | '/docs/form'
    | '/docs/layout'
    | '/docs/navigation'
    | '/docs/overlay'
    | '/docs/theme'
    | '/docs'
    | '/admin/berkas/menu'
    | '/admin/berkas/perusahaan'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/karyawan/dashboard'
    | '/admin/accounting/kasbank/$nobukti'
    | '/admin/reports/laporan/$kodeMenu'
    | '/karyawan/berkas/laporan-dinamis/$kode'
    | '/admin/accounting/kasbank'
    | '/admin/master-data/activity-logs'
    | '/admin/master-data/config-logs'
    | '/admin/master-data/dynamic-browse'
    | '/admin/master-data/laporan-dinamis'
    | '/admin/master-data/users'
    | '/admin/reports/builder'
    | '/admin/reports/laporan'
    | '/admin/reports/permission-report'
    | '/karyawan/berkas/laporan-dinamis'
    | '/admin/reports/builder/$kodemenu/edit'
    | '/admin/reports/builder/$kodemenu/generate'
    | '/admin/master-data/users/$id'
    | '/admin/master-data/users/new'
    | '/admin/master-data/users/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/400'
    | '/404'
    | '/500'
    | '/about'
    | '/(public)/docs'
    | '/admin/_layout'
    | '/karyawan/_layout'
    | '/(public)/docs/data'
    | '/(public)/docs/feedback'
    | '/(public)/docs/form'
    | '/(public)/docs/layout'
    | '/(public)/docs/navigation'
    | '/(public)/docs/overlay'
    | '/(public)/docs/theme'
    | '/(public)/docs/'
    | '/admin/_layout/berkas/menu'
    | '/admin/_layout/berkas/perusahaan'
    | '/admin/_layout/reports/builder'
    | '/admin/_layout/reports/laporan'
    | '/(public)/(auth)/login/'
    | '/(public)/(auth)/register/'
    | '/admin/_layout/dashboard/'
    | '/admin/_layout/documents/'
    | '/karyawan/_layout/dashboard/'
    | '/admin/_layout/accounting/kasbank/$nobukti'
    | '/admin/_layout/reports/laporan/$kodeMenu'
    | '/karyawan/_layout/berkas/laporan-dinamis/$kode'
    | '/admin/_layout/accounting/kasbank/'
    | '/admin/_layout/master-data/activity-logs/'
    | '/admin/_layout/master-data/config-logs/'
    | '/admin/_layout/master-data/dynamic-browse/'
    | '/admin/_layout/master-data/laporan-dinamis/'
    | '/admin/_layout/master-data/users/'
    | '/admin/_layout/reports/builder/'
    | '/admin/_layout/reports/laporan/'
    | '/admin/_layout/reports/permission-report/'
    | '/karyawan/_layout/berkas/laporan-dinamis/'
    | '/admin/_layout/reports/builder/$kodemenu/edit'
    | '/admin/_layout/reports/builder/$kodemenu/generate'
    | '/admin/_layout/master-data/users/$id/'
    | '/admin/_layout/master-data/users/new/'
    | '/admin/_layout/master-data/users/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R400Route: typeof R400Route
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AboutRoute: typeof AboutRoute
  publicDocsRoute: typeof publicDocsRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  KaryawanLayoutRoute: typeof KaryawanLayoutRouteWithChildren
  publicauthLoginIndexRoute: typeof publicauthLoginIndexRoute
  publicauthRegisterIndexRoute: typeof publicauthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/400': {
      id: '/400'
      path: '/400'
      fullPath: '/400'
      preLoaderRoute: typeof R400RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/docs': {
      id: '/(public)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof publicDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karyawan/_layout': {
      id: '/karyawan/_layout'
      path: '/karyawan'
      fullPath: '/karyawan'
      preLoaderRoute: typeof KaryawanLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/docs/': {
      id: '/(public)/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof publicDocsIndexRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/data': {
      id: '/(public)/docs/data'
      path: '/data'
      fullPath: '/docs/data'
      preLoaderRoute: typeof publicDocsDataRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/feedback': {
      id: '/(public)/docs/feedback'
      path: '/feedback'
      fullPath: '/docs/feedback'
      preLoaderRoute: typeof publicDocsFeedbackRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/form': {
      id: '/(public)/docs/form'
      path: '/form'
      fullPath: '/docs/form'
      preLoaderRoute: typeof publicDocsFormRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/layout': {
      id: '/(public)/docs/layout'
      path: '/layout'
      fullPath: '/docs/layout'
      preLoaderRoute: typeof publicDocsLayoutRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/navigation': {
      id: '/(public)/docs/navigation'
      path: '/navigation'
      fullPath: '/docs/navigation'
      preLoaderRoute: typeof publicDocsNavigationRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/overlay': {
      id: '/(public)/docs/overlay'
      path: '/overlay'
      fullPath: '/docs/overlay'
      preLoaderRoute: typeof publicDocsOverlayRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/docs/theme': {
      id: '/(public)/docs/theme'
      path: '/theme'
      fullPath: '/docs/theme'
      preLoaderRoute: typeof publicDocsThemeRouteImport
      parentRoute: typeof publicDocsRoute
    }
    '/(public)/(auth)/login/': {
      id: '/(public)/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof publicauthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/register/': {
      id: '/(public)/(auth)/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof publicauthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/berkas/menu': {
      id: '/admin/_layout/berkas/menu'
      path: '/berkas/menu'
      fullPath: '/admin/berkas/menu'
      preLoaderRoute: typeof AdminLayoutBerkasMenuRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/berkas/perusahaan': {
      id: '/admin/_layout/berkas/perusahaan'
      path: '/berkas/perusahaan'
      fullPath: '/admin/berkas/perusahaan'
      preLoaderRoute: typeof AdminLayoutBerkasPerusahaanRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard/': {
      id: '/admin/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminLayoutDashboardIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/documents/': {
      id: '/admin/_layout/documents/'
      path: '/documents'
      fullPath: '/admin/documents/'
      preLoaderRoute: typeof AdminLayoutDocumentsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reports/builder': {
      id: '/admin/_layout/reports/builder'
      path: '/reports/builder'
      fullPath: '/admin/reports/builder'
      preLoaderRoute: typeof AdminLayoutReportsBuilderRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reports/laporan': {
      id: '/admin/_layout/reports/laporan'
      path: '/reports/laporan'
      fullPath: '/admin/reports/laporan'
      preLoaderRoute: typeof AdminLayoutReportsLaporanRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/karyawan/_layout/dashboard/': {
      id: '/karyawan/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/karyawan/dashboard/'
      preLoaderRoute: typeof KaryawanLayoutDashboardIndexRouteImport
      parentRoute: typeof KaryawanLayoutRoute
    }
    '/admin/_layout/accounting/kasbank/': {
      id: '/admin/_layout/accounting/kasbank/'
      path: '/accounting/kasbank'
      fullPath: '/admin/accounting/kasbank/'
      preLoaderRoute: typeof AdminLayoutAccountingKasbankIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/accounting/kasbank/$nobukti': {
      id: '/admin/_layout/accounting/kasbank/$nobukti'
      path: '/accounting/kasbank/$nobukti'
      fullPath: '/admin/accounting/kasbank/$nobukti'
      preLoaderRoute: typeof AdminLayoutAccountingKasbankNobuktiRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/master-data/activity-logs/': {
      id: '/admin/_layout/master-data/activity-logs/'
      path: '/master-data/activity-logs'
      fullPath: '/admin/master-data/activity-logs/'
      preLoaderRoute: typeof AdminLayoutMasterDataActivityLogsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/master-data/config-logs/': {
      id: '/admin/_layout/master-data/config-logs/'
      path: '/master-data/config-logs'
      fullPath: '/admin/master-data/config-logs/'
      preLoaderRoute: typeof AdminLayoutMasterDataConfigLogsIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/master-data/dynamic-browse/': {
      id: '/admin/_layout/master-data/dynamic-browse/'
      path: '/master-data/dynamic-browse'
      fullPath: '/admin/master-data/dynamic-browse/'
      preLoaderRoute: typeof AdminLayoutMasterDataDynamicBrowseIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/master-data/laporan-dinamis/': {
      id: '/admin/_layout/master-data/laporan-dinamis/'
      path: '/master-data/laporan-dinamis'
      fullPath: '/admin/master-data/laporan-dinamis/'
      preLoaderRoute: typeof AdminLayoutMasterDataLaporanDinamisIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/master-data/users/': {
      id: '/admin/_layout/master-data/users/'
      path: '/master-data/users'
      fullPath: '/admin/master-data/users/'
      preLoaderRoute: typeof AdminLayoutMasterDataUsersIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reports/builder/': {
      id: '/admin/_layout/reports/builder/'
      path: '/'
      fullPath: '/admin/reports/builder/'
      preLoaderRoute: typeof AdminLayoutReportsBuilderIndexRouteImport
      parentRoute: typeof AdminLayoutReportsBuilderRoute
    }
    '/admin/_layout/reports/laporan/': {
      id: '/admin/_layout/reports/laporan/'
      path: '/'
      fullPath: '/admin/reports/laporan/'
      preLoaderRoute: typeof AdminLayoutReportsLaporanIndexRouteImport
      parentRoute: typeof AdminLayoutReportsLaporanRoute
    }
    '/admin/_layout/reports/laporan/$kodeMenu': {
      id: '/admin/_layout/reports/laporan/$kodeMenu'
      path: '/$kodeMenu'
      fullPath: '/admin/reports/laporan/$kodeMenu'
      preLoaderRoute: typeof AdminLayoutReportsLaporanKodeMenuRouteImport
      parentRoute: typeof AdminLayoutReportsLaporanRoute
    }
    '/admin/_layout/reports/permission-report/': {
      id: '/admin/_layout/reports/permission-report/'
      path: '/reports/permission-report'
      fullPath: '/admin/reports/permission-report/'
      preLoaderRoute: typeof AdminLayoutReportsPermissionReportIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/karyawan/_layout/berkas/laporan-dinamis/': {
      id: '/karyawan/_layout/berkas/laporan-dinamis/'
      path: '/berkas/laporan-dinamis'
      fullPath: '/karyawan/berkas/laporan-dinamis/'
      preLoaderRoute: typeof KaryawanLayoutBerkasLaporanDinamisIndexRouteImport
      parentRoute: typeof KaryawanLayoutRoute
    }
    '/karyawan/_layout/berkas/laporan-dinamis/$kode': {
      id: '/karyawan/_layout/berkas/laporan-dinamis/$kode'
      path: '/berkas/laporan-dinamis/$kode'
      fullPath: '/karyawan/berkas/laporan-dinamis/$kode'
      preLoaderRoute: typeof KaryawanLayoutBerkasLaporanDinamisKodeRouteImport
      parentRoute: typeof KaryawanLayoutRoute
    }
    '/admin/_layout/master-data/users/$id/': {
      id: '/admin/_layout/master-data/users/$id/'
      path: '/master-data/users/$id'
      fullPath: '/admin/master-data/users/$id/'
      preLoaderRoute: typeof AdminLayoutMasterDataUsersIdIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/master-data/users/new/': {
      id: '/admin/_layout/master-data/users/new/'
      path: '/master-data/users/new'
      fullPath: '/admin/master-data/users/new/'
      preLoaderRoute: typeof AdminLayoutMasterDataUsersNewIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reports/builder/$kodemenu/edit': {
      id: '/admin/_layout/reports/builder/$kodemenu/edit'
      path: '/$kodemenu/edit'
      fullPath: '/admin/reports/builder/$kodemenu/edit'
      preLoaderRoute: typeof AdminLayoutReportsBuilderKodemenuEditRouteImport
      parentRoute: typeof AdminLayoutReportsBuilderRoute
    }
    '/admin/_layout/reports/builder/$kodemenu/generate': {
      id: '/admin/_layout/reports/builder/$kodemenu/generate'
      path: '/$kodemenu/generate'
      fullPath: '/admin/reports/builder/$kodemenu/generate'
      preLoaderRoute: typeof AdminLayoutReportsBuilderKodemenuGenerateRouteImport
      parentRoute: typeof AdminLayoutReportsBuilderRoute
    }
    '/admin/_layout/master-data/users/$id/edit/': {
      id: '/admin/_layout/master-data/users/$id/edit/'
      path: '/master-data/users/$id/edit'
      fullPath: '/admin/master-data/users/$id/edit/'
      preLoaderRoute: typeof AdminLayoutMasterDataUsersIdEditIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface publicDocsRouteChildren {
  publicDocsDataRoute: typeof publicDocsDataRoute
  publicDocsFeedbackRoute: typeof publicDocsFeedbackRoute
  publicDocsFormRoute: typeof publicDocsFormRoute
  publicDocsLayoutRoute: typeof publicDocsLayoutRoute
  publicDocsNavigationRoute: typeof publicDocsNavigationRoute
  publicDocsOverlayRoute: typeof publicDocsOverlayRoute
  publicDocsThemeRoute: typeof publicDocsThemeRoute
  publicDocsIndexRoute: typeof publicDocsIndexRoute
}

const publicDocsRouteChildren: publicDocsRouteChildren = {
  publicDocsDataRoute: publicDocsDataRoute,
  publicDocsFeedbackRoute: publicDocsFeedbackRoute,
  publicDocsFormRoute: publicDocsFormRoute,
  publicDocsLayoutRoute: publicDocsLayoutRoute,
  publicDocsNavigationRoute: publicDocsNavigationRoute,
  publicDocsOverlayRoute: publicDocsOverlayRoute,
  publicDocsThemeRoute: publicDocsThemeRoute,
  publicDocsIndexRoute: publicDocsIndexRoute,
}

const publicDocsRouteWithChildren = publicDocsRoute._addFileChildren(
  publicDocsRouteChildren,
)

interface AdminLayoutReportsBuilderRouteChildren {
  AdminLayoutReportsBuilderIndexRoute: typeof AdminLayoutReportsBuilderIndexRoute
  AdminLayoutReportsBuilderKodemenuEditRoute: typeof AdminLayoutReportsBuilderKodemenuEditRoute
  AdminLayoutReportsBuilderKodemenuGenerateRoute: typeof AdminLayoutReportsBuilderKodemenuGenerateRoute
}

const AdminLayoutReportsBuilderRouteChildren: AdminLayoutReportsBuilderRouteChildren =
  {
    AdminLayoutReportsBuilderIndexRoute: AdminLayoutReportsBuilderIndexRoute,
    AdminLayoutReportsBuilderKodemenuEditRoute:
      AdminLayoutReportsBuilderKodemenuEditRoute,
    AdminLayoutReportsBuilderKodemenuGenerateRoute:
      AdminLayoutReportsBuilderKodemenuGenerateRoute,
  }

const AdminLayoutReportsBuilderRouteWithChildren =
  AdminLayoutReportsBuilderRoute._addFileChildren(
    AdminLayoutReportsBuilderRouteChildren,
  )

interface AdminLayoutReportsLaporanRouteChildren {
  AdminLayoutReportsLaporanKodeMenuRoute: typeof AdminLayoutReportsLaporanKodeMenuRoute
  AdminLayoutReportsLaporanIndexRoute: typeof AdminLayoutReportsLaporanIndexRoute
}

const AdminLayoutReportsLaporanRouteChildren: AdminLayoutReportsLaporanRouteChildren =
  {
    AdminLayoutReportsLaporanKodeMenuRoute:
      AdminLayoutReportsLaporanKodeMenuRoute,
    AdminLayoutReportsLaporanIndexRoute: AdminLayoutReportsLaporanIndexRoute,
  }

const AdminLayoutReportsLaporanRouteWithChildren =
  AdminLayoutReportsLaporanRoute._addFileChildren(
    AdminLayoutReportsLaporanRouteChildren,
  )

interface AdminLayoutRouteChildren {
  AdminLayoutBerkasMenuRoute: typeof AdminLayoutBerkasMenuRoute
  AdminLayoutBerkasPerusahaanRoute: typeof AdminLayoutBerkasPerusahaanRoute
  AdminLayoutReportsBuilderRoute: typeof AdminLayoutReportsBuilderRouteWithChildren
  AdminLayoutReportsLaporanRoute: typeof AdminLayoutReportsLaporanRouteWithChildren
  AdminLayoutDashboardIndexRoute: typeof AdminLayoutDashboardIndexRoute
  AdminLayoutDocumentsIndexRoute: typeof AdminLayoutDocumentsIndexRoute
  AdminLayoutAccountingKasbankNobuktiRoute: typeof AdminLayoutAccountingKasbankNobuktiRoute
  AdminLayoutAccountingKasbankIndexRoute: typeof AdminLayoutAccountingKasbankIndexRoute
  AdminLayoutMasterDataActivityLogsIndexRoute: typeof AdminLayoutMasterDataActivityLogsIndexRoute
  AdminLayoutMasterDataConfigLogsIndexRoute: typeof AdminLayoutMasterDataConfigLogsIndexRoute
  AdminLayoutMasterDataDynamicBrowseIndexRoute: typeof AdminLayoutMasterDataDynamicBrowseIndexRoute
  AdminLayoutMasterDataLaporanDinamisIndexRoute: typeof AdminLayoutMasterDataLaporanDinamisIndexRoute
  AdminLayoutMasterDataUsersIndexRoute: typeof AdminLayoutMasterDataUsersIndexRoute
  AdminLayoutReportsPermissionReportIndexRoute: typeof AdminLayoutReportsPermissionReportIndexRoute
  AdminLayoutMasterDataUsersIdIndexRoute: typeof AdminLayoutMasterDataUsersIdIndexRoute
  AdminLayoutMasterDataUsersNewIndexRoute: typeof AdminLayoutMasterDataUsersNewIndexRoute
  AdminLayoutMasterDataUsersIdEditIndexRoute: typeof AdminLayoutMasterDataUsersIdEditIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutBerkasMenuRoute: AdminLayoutBerkasMenuRoute,
  AdminLayoutBerkasPerusahaanRoute: AdminLayoutBerkasPerusahaanRoute,
  AdminLayoutReportsBuilderRoute: AdminLayoutReportsBuilderRouteWithChildren,
  AdminLayoutReportsLaporanRoute: AdminLayoutReportsLaporanRouteWithChildren,
  AdminLayoutDashboardIndexRoute: AdminLayoutDashboardIndexRoute,
  AdminLayoutDocumentsIndexRoute: AdminLayoutDocumentsIndexRoute,
  AdminLayoutAccountingKasbankNobuktiRoute:
    AdminLayoutAccountingKasbankNobuktiRoute,
  AdminLayoutAccountingKasbankIndexRoute:
    AdminLayoutAccountingKasbankIndexRoute,
  AdminLayoutMasterDataActivityLogsIndexRoute:
    AdminLayoutMasterDataActivityLogsIndexRoute,
  AdminLayoutMasterDataConfigLogsIndexRoute:
    AdminLayoutMasterDataConfigLogsIndexRoute,
  AdminLayoutMasterDataDynamicBrowseIndexRoute:
    AdminLayoutMasterDataDynamicBrowseIndexRoute,
  AdminLayoutMasterDataLaporanDinamisIndexRoute:
    AdminLayoutMasterDataLaporanDinamisIndexRoute,
  AdminLayoutMasterDataUsersIndexRoute: AdminLayoutMasterDataUsersIndexRoute,
  AdminLayoutReportsPermissionReportIndexRoute:
    AdminLayoutReportsPermissionReportIndexRoute,
  AdminLayoutMasterDataUsersIdIndexRoute:
    AdminLayoutMasterDataUsersIdIndexRoute,
  AdminLayoutMasterDataUsersNewIndexRoute:
    AdminLayoutMasterDataUsersNewIndexRoute,
  AdminLayoutMasterDataUsersIdEditIndexRoute:
    AdminLayoutMasterDataUsersIdEditIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

interface KaryawanLayoutRouteChildren {
  KaryawanLayoutDashboardIndexRoute: typeof KaryawanLayoutDashboardIndexRoute
  KaryawanLayoutBerkasLaporanDinamisKodeRoute: typeof KaryawanLayoutBerkasLaporanDinamisKodeRoute
  KaryawanLayoutBerkasLaporanDinamisIndexRoute: typeof KaryawanLayoutBerkasLaporanDinamisIndexRoute
}

const KaryawanLayoutRouteChildren: KaryawanLayoutRouteChildren = {
  KaryawanLayoutDashboardIndexRoute: KaryawanLayoutDashboardIndexRoute,
  KaryawanLayoutBerkasLaporanDinamisKodeRoute:
    KaryawanLayoutBerkasLaporanDinamisKodeRoute,
  KaryawanLayoutBerkasLaporanDinamisIndexRoute:
    KaryawanLayoutBerkasLaporanDinamisIndexRoute,
}

const KaryawanLayoutRouteWithChildren = KaryawanLayoutRoute._addFileChildren(
  KaryawanLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R400Route: R400Route,
  R404Route: R404Route,
  R500Route: R500Route,
  AboutRoute: AboutRoute,
  publicDocsRoute: publicDocsRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  KaryawanLayoutRoute: KaryawanLayoutRouteWithChildren,
  publicauthLoginIndexRoute: publicauthLoginIndexRoute,
  publicauthRegisterIndexRoute: publicauthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
